= Cheatsheet C#

== CaseINsensitive maken
string ... .Equals(input, StringComparison.CurrentCultureIgnoreCase)

== Shortcuts
* ctor = constructor
* prop/prod =  properties
* Document formatteren: ctrl + k ctrl + d
* For C# code files, Visual Studio 2019 has a Code Cleanup button at the bottom of the editor (keyboard: Ctrl+K, Ctrl+E) to apply code styles from an EditorConfig file or from the Code Style options page.

== Loops
===
Alles wat je in een loop zet is bij het eindigen van de loop buiten scope aka verdwenen.
====

== Forloop
Een _loop_ met een tellervariabele heeft drie onderdelen :

. *beginwaarde* van de tellervariabele
. _loop_ voorwaarde gebaseerd op de teller
. *aanpassing* van de teller

In een **__for loop__** structuur worden deze drie onderdelen gebundeld in de hoofding (i.e. de eerste regel van de for loop), zodat je ze makkelijk terugvindt en herkent. 

De algemene vorm van een __for loop__ is :

[source,csharp,linenums]
----
for (beginwaarde ; voorwaarde ; aanpassing) {
    code block
}
----

De voorwaarde vergelijkt normaliter de teller met een of andere *grenswaarde* die niet mag overschreden worden.

Heel vaak is de teller enkel relevant tijdens de _loop_ en niet daarbuiten. In zo'n geval plaatsen we de declaratie van de tellervariabele meteen bij het _beginwaarde_ gedeelte van hoofding.

[IMPORTANT]
====
De tellervariabele is zo goed al altijd van type `int`.

Als de tellervariabele in de hoofding wordt gedeclareerd, is zijn _scope_ gelijk aan de __loop body__. Voor en na de __for loop__ is de variabele dus __out of scope__!
====

Indien de teller geen echte betekenis heeft en van type `int` is, gebruikt men gewoonlijk de namen `i`, `j` of `k`.

|====
|De teller .. | Kenmerken van de for loop

|stijgt, loopt op, wordt groter, klimt
a|
- beginwaarde is lager dan de grenswaarde
- stapgrootte is positief
- voorwaarde vergelijkt teller met grenswaarde op basis van `<` of `\<=`
|zakt, neemt af, wordt kleiner, daalt
a|
- beginwaarde is hoger dan de grenswaarde
- stapgrootte is negatief
- voorwaarde vergelijkt teller met grenswaarde op basis van `>` of `>=`
|====
In de voorwaarde van een for loop vergelijk je teller en grenswaarde doorgaans niet met `!=` (al is dat niet verkeerde).