= Programmeren Basis - Deel PA
Yanic Inghelbrecht
v2020.11.25.15.00
// toc and section numbering
:toc: preamble
:toclevels: 4
:sectnums: 
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}
 
== Personen applicatie

Deze applicatie dient als voorbeeld van een wat grotere console applicatie. We gebruiken ze om te demonstreren hoe een aantal technieken het makkelijker kunnen maken om een groter programma te organiseren.

=== Startpunt

Kopieer onderstaande code in een `Main` method, bv. in het bestand `Program.cs` dat we al van bij het begin van deze cursus gebruiken.

Start nu het programma en probeer alle mogelijkheden eens uit, zodat je goed weet wat de mogelijkheden zijn. Probeer hier en daar ook eens foutieve input te geven zodat je ziet hoe het programma daarop reageert.

[source,csharp,linenums]
----
const int maxPersonen = 20;

const int keuzeVoegToe = 1;
const int keuzeVerwijder = 2;
const int keuzeBewerk = 3;
const int keuzeToon = 4;
const int keuzeStop = 5;

string[] voornamen = new string[maxPersonen];
string[] familienamen = new string[maxPersonen];
bool[] isVrouwen = new bool[maxPersonen];
string[] postcodes = new string[maxPersonen];
string[] gemeenten = new string[maxPersonen];
int[] aantalKinderen = new int[maxPersonen];
int aantalPersonen = 0;

voornamen[aantalPersonen] = "Jan";
familienamen[aantalPersonen] = "Janssens";
isVrouwen[aantalPersonen] = false;
postcodes[aantalPersonen] = "8501";
gemeenten[aantalPersonen] = "Heule";
aantalKinderen[aantalPersonen] = 2;
aantalPersonen++;

voornamen[aantalPersonen] = "Mieke";
familienamen[aantalPersonen] = "Mickelsen";
isVrouwen[aantalPersonen] = true;
postcodes[aantalPersonen] = "9000";
gemeenten[aantalPersonen] = "Gent";
aantalKinderen[aantalPersonen] = 0;
aantalPersonen++;

int keuze = 0;
bool isCorrectAntwoord;
do {
	Console.Clear();
	Console.WriteLine("Gekende personen");
	Console.WriteLine("----------------");
	for (int i = 0; i < aantalPersonen; i++) {
		Console.WriteLine($"{i,2} {voornamen[i]} {familienamen[i]}, {gemeenten[i]}");
	}

	Console.WriteLine();
	Console.WriteLine("Hoofdmenu");
	Console.WriteLine("---------");
	Console.WriteLine("1) een persoon toevoegen");
	Console.WriteLine("2) een persoon verwijderen");
	Console.WriteLine("3) een persoon aanpassen");
	Console.WriteLine("4) alle details van een persoon zien");
	Console.WriteLine("5) stoppen");
	Console.WriteLine();

	do {
		Console.Write("Wat wil u doen : ");
		string keuzeAlsTekst = Console.ReadLine().Trim();
		bool isGeldig = int.TryParse(keuzeAlsTekst, out keuze);
		isCorrectAntwoord = isGeldig && (keuze >= keuzeVoegToe && keuze <= keuzeStop);
	} while (!isCorrectAntwoord);
	Console.WriteLine();

	if (keuze == keuzeVoegToe) {
		Console.WriteLine("Persoon toevoegen");
		Console.WriteLine("-----------------");

		string antwoord;

		do {
			Console.Write("Voornaam : ");
			antwoord = Console.ReadLine().Trim();
		} while (antwoord == "");
		voornamen[aantalPersonen] = antwoord;

		do {
			Console.Write("Familienaam : ");
			antwoord = Console.ReadLine().Trim();
		} while (antwoord == "");
		familienamen[aantalPersonen] = antwoord;

		do {
			Console.Write("Geslacht (m/v) : ");
			antwoord = Console.ReadLine().Trim().ToLower();
		} while (antwoord != "m" && antwoord != "v");
		isVrouwen[aantalPersonen] = (antwoord == "v");

		do {
			Console.Write("Postcode : ");
			antwoord = Console.ReadLine().Trim();
		} while (antwoord == "");
		postcodes[aantalPersonen] = antwoord;

		do {
			Console.Write("Gemeente : ");
			antwoord = Console.ReadLine().Trim();
		} while (antwoord == "");
		gemeenten[aantalPersonen] = antwoord;

		int aantal;
		do {
			Console.Write("Aantal kinderen : ");
			string aantalKinderenAlsTekst = Console.ReadLine().Trim();
			bool isGetal = int.TryParse(aantalKinderenAlsTekst, out aantal);
			isCorrectAntwoord = isGetal && (aantal >= 0);
		} while (!isCorrectAntwoord);
		aantalKinderen[aantalPersonen] = aantal;

		Console.WriteLine();
		Console.WriteLine("Ingevoerde gegevens");
		Console.WriteLine("-------------------");
		Console.WriteLine("voornaam    : " + voornamen[aantalPersonen]);
		Console.WriteLine("familienaam : " + familienamen[aantalPersonen]);
		Console.WriteLine("geslacht    : " + (isVrouwen[aantalPersonen] ? "vrouw" : "man"));
		Console.WriteLine("postcode    : " + postcodes[aantalPersonen]);
		Console.WriteLine("gemeente    : " + gemeenten[aantalPersonen]);
		Console.WriteLine("kinderen    : " + aantalKinderen[aantalPersonen]);
		do {
			Console.Write("Wil u deze gegevens bewaren (j/n) : ");
			antwoord = Console.ReadLine().Trim().ToLower();
		} while (antwoord != "j" && antwoord != "n");
		if (antwoord == "j") {
			aantalPersonen++;
		}

	} else if (keuze == keuzeVerwijder) {
		Console.WriteLine("Persoon verwijderen");
		Console.WriteLine("-------------------");

		int index;
		do {
			Console.Write("Welke persoon wil u verwijderen : ");
			string indexAlsTekst = Console.ReadLine().Trim();
			bool isGeldig = int.TryParse(indexAlsTekst, out index);
			isCorrectAntwoord = isGeldig && (index >= 0 && index < aantalPersonen);
		} while (!isCorrectAntwoord);

		// toon detail van persoon op positie 'index'
		Console.WriteLine("voornaam    : " + voornamen[index]);
		Console.WriteLine("familienaam : " + familienamen[index]);
		Console.WriteLine("geslacht    : " + (isVrouwen[index] ? "vrouw" : "man"));
		Console.WriteLine("postcode    : " + postcodes[index]);
		Console.WriteLine("gemeente    : " + gemeenten[index]);
		Console.WriteLine("kinderen    : " + aantalKinderen[index]);

		string antwoord;
		do {
			Console.Write("Wil u de gegevens van deze persoon daadwerkelijk verwijderen (j/n) : ");
			antwoord = Console.ReadLine().Trim().ToLower();
		} while (antwoord != "j" && antwoord != "n");
		if (antwoord == "j") {
			// verwijder de persoon op positie 'index'
			for (int i = index; i < aantalPersonen - 1; i++) {
				voornamen[i] = voornamen[i + 1];
				familienamen[i] = familienamen[i + 1];
				isVrouwen[i] = isVrouwen[i + 1];
				postcodes[i] = postcodes[i + 1];
				gemeenten[i] = gemeenten[i + 1];
				aantalKinderen[i] = aantalKinderen[i + 1];
			}
			aantalPersonen--;
		}
	} else if (keuze == keuzeBewerk) {
		Console.WriteLine("Persoon bewerken");
		Console.WriteLine("----------------");

		int index;
		do {
			Console.Write("Welke persoon wil u bewerken : ");
			string indexAlsTekst = Console.ReadLine().Trim();
			bool isGeldig = int.TryParse(indexAlsTekst, out index);
			isCorrectAntwoord = isGeldig && (index >= 0 && index < aantalPersonen);
		} while (!isCorrectAntwoord);

		Console.WriteLine("Indien u een gegeven ongewijzigd wil laten, druk dan gewoon op enter.");

		Console.Write("Voornaam : ");
		string voornaam = Console.ReadLine().Trim();

		Console.Write("Familienaam : ");
		string familienaam = Console.ReadLine().Trim();

		string geslacht;
		do {
			Console.Write("Geslacht (m/v) : ");
			geslacht = Console.ReadLine().Trim().ToLower();
		} while (geslacht != "" && geslacht != "m" && geslacht != "v");

		Console.Write("Postcode : ");
		string postcode = Console.ReadLine().Trim();

		Console.Write("Gemeente : ");
		string gemeente = Console.ReadLine().Trim();

		int aantal = -1;
		do {
			Console.Write("Aantal kinderen : ");
			string aantalKinderenAlsTekst = Console.ReadLine().Trim();
			if (aantalKinderenAlsTekst == "") {
				isCorrectAntwoord = true;
			} else {
				bool isGeldig = int.TryParse(aantalKinderenAlsTekst, out aantal);
				isCorrectAntwoord = isGeldig && (aantal >= 0);
			}
		} while (!isCorrectAntwoord);

		Console.WriteLine();
		Console.WriteLine("Gewijzigde gegevens");
		Console.WriteLine("-------------------");
		if (voornaam != "") {
			Console.WriteLine("voornaam    : " + voornaam);
		}
		if (familienaam != "") {
			Console.WriteLine("familienaam : " + familienaam);
		}
		if (geslacht != "") {
			Console.WriteLine("geslacht    : " + (geslacht == "v" ? "vrouw" : "man"));
		}
		if (postcode != "") {
			Console.WriteLine("postcode    : " + postcode);
		}
		if (gemeente != "") {
			Console.WriteLine("gemeente    : " + gemeente);
		}
		if (aantal != -1) {
			Console.WriteLine("kinderen    : " + aantal);
		}

		string antwoord;
		do {
			Console.Write("Wil u deze wijziging(en) bewaren (j/n) : ");
			antwoord = Console.ReadLine().Trim().ToLower();
		} while (antwoord != "j" && antwoord != "n");
		if (antwoord == "j") {
			if (voornaam!="") {
				voornamen[index] = voornaam;
			}
			if (familienaam != "") {
				familienamen[index] = familienaam;
			}
			if (geslacht != "") {
				isVrouwen[index] = (geslacht == "v");
			}
			if (postcode != "") {
				postcodes[index] = postcode;
			}
			if (gemeente != "") {
				gemeenten[index] = gemeente;
			}
			if (aantal != -1) {
				aantalKinderen[index] = aantal;
			}
		}
	} else if (keuze == keuzeToon) {
		int index;
		do {
			Console.Write("Van welke persoon wil u de details zien : ");
			string indexAlsTekst = Console.ReadLine().Trim();
			bool isGeldig = int.TryParse(indexAlsTekst, out index);
			isCorrectAntwoord = isGeldig && (index >= 0 && index < aantalPersonen);
		} while (!isCorrectAntwoord);

		// toon detail van persoon op positie 'index'
		Console.WriteLine("voornaam    : " + voornamen[index]);
		Console.WriteLine("familienaam : " + familienamen[index]);
		Console.WriteLine("geslacht    : " + (isVrouwen[index] ? "vrouw" : "man"));
		Console.WriteLine("postcode    : " + postcodes[index]);
		Console.WriteLine("gemeente    : " + gemeenten[index]);
		Console.WriteLine("kinderen    : " + aantalKinderen[index]);
		Console.WriteLine();
		Console.WriteLine("Druk op enter om terug te keren naar het hoofdmenu");
		Console.ReadLine();
	}

} while (keuze != keuzeStop);

----

=== Inzicht in de werking

Nu je goed weet wat het programma kan, is het tijd om de code erbij te pakken.

Bestudeer de code in de hieronder aangehaalde volgorde en beantwoord alle vragen. 

[TIP]
====
Het kan verhelderend zijn om sommige stukken van het programma ook eens met de debugger te doorlopen!
====

==== Het overkoepelende menu

Ga na hoe het programma het menu toont en de gebruikers input verwerkt. 

. Waarom eindigt het programma pas als de gebruiker keuze `5` kiest?

. Wat bepaalt dat keuze `4` in het menu de 'alle details van een persoon zien' functionaliteit in gang steekt?

==== Keuze : alle details van een persoon zien

Bekijk aandachtig de code van dit gedeelte en de gebruikte variabelen.

. Het programma gaat pas verder als je een geldige persoon gekozen hebt, waar gebeurt dit?
. Hoe is de informatie van één persoon over de verschillende arrays verdeeld?
. Waarvoor dient de variabele `aantalPersonen` in verband met de arrays?
. Hoe komt de initiële data in het programma terecht (i.e. de info over Jan en Mieke)?
. Hoe wordt de `true`/`false` waarde voor `isVrouw` omgezet naar `vrouw`/`man` in de output?
** Zie link:https://wellsb.com/csharp/beginners/csharp-ternary-conditional-operator/[]

==== Keuze : een persoon toevoegen

Bekijk aandachtig de code van dit gedeelte en de gebruikte variabelen.

. Hoe zorgt het programma ervoor dat lege tekst niet aanvaard wordt als voornaam?
. Waarom hoeft er bij het geslacht niet op een lege string gecontroleerd te worden?
. Hoe wordt de `m`/`v` input bij geslacht, omgezet naar een `false`/`true` waarde voor `isVrouw`?
. Hoe wordt de ingevoerde data onthouden zolang het programma nog geen antwoord heeft op de `Wil u deze gegevens bewaren (j/n)?` vraag?
. Waarom moet deze onthouden data niet expliciet verwijderd worden als de gebruiker deze vraag met `n` beantwoordt?

==== Keuze : een persoon aanpassen

Bekijk aandachtig de code van dit gedeelte en de gebruikte variabelen.

. Waarom is lege input bij voornaam dit keer WEL aanvaardbaar (i.t.t. bij het toevoegen)?
. Hoe wordt er omgegaan met lege input voor het aantal kinderen en waarom is -1 ok in dit geval?
. Wat zou je doen als ALLE mogelijke `int` waarden geldig zouden zijn om 'lege input' aan te duiden?
. Hoe weet het programma of de voornaam moet overschreven worden?
. Hoe weet het programma of het aantal kinderen moet overschreven worden?

==== Keuze : een persoon verwijderen

Bekijk aandachtig de code van dit gedeelte en de gebruikte variabelen.

. Hoe gaat het verwijderen in z'n werk?
. Wat doen al die array manipulaties in de loop eigenlijk?
. Waarom moeten er in de arrays geen waarden op `0`/`false`/`null` gezet worden bij het verwijderen?

==== Varia

. Hoe kun je (als gebruiker) het programma in zo'n toestand krijgen dat de gebruiker onmogelijk nog input kan geven die door het programma aanvaard wordt?
. Hoe kun je het programma laten crashen met een `IndexOutOfRangeException`?
. Wat vind je van de scope van de variabele isCorrectAntwoord, is die te ruim of net goed? 
** Indien te ruim, hoe zou je de scope dan (beperkter) kiezen?
** Indien net goed, waarom mag de scope niet beperkter zijn?
. Is de variabele aantalPersonen vermijdbaar? 
** Indien wel, hoe zou je de code aanpassen zodat deze overbodig wordt? (de aanpak uitleggen, je hoeft het NIET in de code aan te passen)
** Indien niet, waarom niet?
. Kan het verwijderen van een persoon gerealiseerd worden zonder al die array verschuivingen?
** Indien wel, hoe zou je de code aanpassen zodat deze overbodig wordt? (de aanpak uitleggen, je hoeft het NIET in de code aan te passen)
** Indien niet, waarom niet?


