= Programmeren Basis - Deel 02 - Oefeningen
Yanic Inghelbrecht
v2021.10.01.09.58
// toc and section numbering
:toc: preamble
:toclevels: 4
// geen auto section numbering voor oefeningen (handigere titels en toc)
//:sectnums: 
:sectlinks:
:sectnumlevels: 4
// source code formatting
:prewrap!:
:source-highlighter: rouge
:source-language: csharp
:rouge-style: github
:rouge-css: class
// inject css for highlights using docinfo
:docinfodir: ../common
:docinfo: shared-head
// folders
:imagesdir: images
:url-verdieping: ../{docname}-verdieping/{docname}-verdieping.adoc
// experimental voor kdb: en btn: macro's van AsciiDoctor
:experimental:

//preamble
[.text-right]
versie {revnumber}
 

== String concatenatie en input/output
 
 
=== Oefening D02.frietjes
// Y2.01
Schrijf een programma dat de gebruiker om 2 namen (bv. Jan en Mieke) alsook een gerecht (bv. frietjes) vraagt en vervolgens `Jan en Mieke eten graag frietjes.` op de console zet.

Een uitvoering van het programma ziet er zo uit :

[source,shell]
----
Geef een naam : Jan
Geef nog een naam : Mieke
Geef een gerecht : frietjes
Jan en Mieke eten graag frietjes.
----


=== Oefening D02.leeftijd
// Y2.03
Schrijf een programma dat de gebruiker om zijn/haar naam (bv. Jan) en leeftijd (bv. 34) vraagt en volgende zinnetje op de console zet :

`Goeiedag Jan, je bent dus 34 jaar oud!`

Een uitvoering van het programma ziet er zo uit :

[source,shell]
----
Geef je naam : Jan
Geef je leeftijd : 34
Goeiedag Jan, je bent dus 34 jaar oud!
----

== Conversie
 
 
=== Oefening D02.leeftijdvolgendjaar
// Y2.04
Schrijf een programma dat de gebruiker om zijn/haar naam (bv. Jan) en leeftijd (bv. 34), er een jaartje bijtelt en het volgende zinnetje toont :

`Oei oei Jan, volgend jaar ben je al 35 jaar oud!`

Een uitvoering van het programma ziet er zo uit :

[source,shell]
----
Geef je naam : Jan
Geef je leeftijd : 34
Oei oei Jan, volgend jaar ben je al 35 jaar oud!
----


=== Oefening D02.som
// Y2.02
Schrijf een programma dat de gebruiker om 2 gehele getallen vraagt (bv. 5 en 6) en hun som op de console zet :

`5 plus 6 is 11.`


=== Oefening D02.totalebedrag
// C03
Maak een programma dat de gebruiker vraagt hoeveel muntstukken van 2 en 1 euro hij heeft en vervolgens het totale bedrag toont. 

Een uitvoering ziet er zo uit :

[source,shell]
----
Aantal muntstukken van 2 euro : 4
Aantal muntstukken van 1 euro : 3
Het totale bedrag is 11 Euro.
----


=== Oefening D02.gemiddelde
// Y2.05
Schrijf een programma dat de gebruiker om drie kommagetallen vraagt en hun gemiddelde toont.

			
=== Oefening D02.temperatuur
// Y2.07
Schrijf een programma dat de gebruiker om een temperatuur in graden Fahrenheit (een kommagetal) vraagt en dan de corresponderende de temperatuur in graden Celsius (een kommagetal) toont.

De formule voor de omzetting van graden Fahrenheit (F) naar graden Celsius \(C)  is :
====
C = 5/9 * (F-32)
====

Tip : pas op met gehele delingen, i.e. delingen van gehele getallen!



=== Oefening D02.getalontleden
// Y2.10
Schrijf een programma dat de gebruiker om een geheel getal in [0,1000[ vraagt (dus van 0 t.e.m. 999) en vervolgens toont uit hoeveel honderdtallen, tientallen en eenheden dit bestaat. 

Tip : gebruik deling en modulo.

Een uitvoering met 123 als input ziet er zo uit :
[source,shell]
----
Geef een getal : 123
Het getal 123 bestaat uit
1 x 100
2 x  10
3 x   1
----


== Controlestructuren if en if/else


=== Oefening D02.volwassen
// Y2.14
Schrijf een programma dat de gebruiker om zijn/haar leeftijd vraagt en toont `Je bent wel volwassen.` of `Je bent niet volwassen.`. Volwassen betekent 18 jaar of ouder. 

Gebruik in je code enkel de voorwaarde `leeftijd >= 18`.


=== Oefening D02.gelijk
// Y2.15
Schrijf een programma dat de gebruiker om 2 gehele getallen vraagt en ofwel meldt `Ze zijn gelijk.` ofwel `Ze zijn verschillend.`.

		
=== Oefening D02.quotient
// C05
Maak een programma dat de gebruiker om een deeltal en een deler vraagt en vervolgens het quotient op de console toont.

Indien de gebruiker voor de deler een nul invoert, is de deling niet toegelaten en wordt dit gemeld.

Een voorbeeld uitvoering :
[source,shell] 
----
Deeltal?: 10,6
Deler?: 5,1
Quotient: 2,07843137254902
----
Merk op dat je taalinstellingen er misschien voor zullen zorgen dat er `2.07843137254902` verschijnt (met een punt dus), dat is ook ok.

Een voorbeeld uitvoering met een nul als deler :
[source,shell]
----
Deeltal?: 10,6
Deler?: 0
Deling door nul wordt niet toegelaten.
----


=== Oefening D02.even
// Y2.16
Schrijf een programma dat de gebruiker om een geheel getal vraagt en ofwel meldt of het getal even dan wel oneven is.

Tip : denk aan modulo 2!

=== Oefening D02.absolutewaarde
// Y2.17
Schrijf een programma dat de gebruiker om een getal vraagt en de absolute waarde van dit getal toont.

De absolute waarde 

- van een positief getal is het getal zelf
- van een negatief getal is het getal zonder minteken ervoor

Tip : Om het minteken weg te krijgen kun je bv. vermenigvuldigen met `-1`, want `-1 * (-10)` geeft `10`.

